version: '3'
services:
  api:
    build: 
      context: .
      dockerfile: Express
#    restart: never
    expose:
      - 3000
    ports: 
      - '3000:3000'
      - '5858:5858'
    volumes:
      - ./:/usr/src/app
    depends_on: 
      - prisma
      - mysql
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_ENDPOINT: http://prisma:4466
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            host: mysql
            port: 3306
            user: root
            password: prisma
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql: ~
