---
language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm
    - .jest
before_install:
  - cd okaysov2
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  - npm test